import streamlit as st
from pypdf import PdfReader
from groq import Groq
import re
from dotenv import load_dotenv
import os
import time
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

# ================= ENV =================

load_dotenv()
api_key = os.getenv("GROQ_API_KEY")

# ================= PAGE =================

st.set_page_config(
    page_title="AI Resume Analyzer (LLM-Based ATS)",
    layout="wide"
)

st.title("📁 AI Resume Analyzer (LLM ATS System)")

# ================= SESSION =================

if "form_submitted" not in st.session_state:
    st.session_state.form_submitted = False
if "resume" not in st.session_state:
    st.session_state.resume = ""
if "job_desc" not in st.session_state:
    st.session_state.job_desc = ""
if "ai_score" not in st.session_state:
    st.session_state.ai_score = 0

# ================= RESET =================

def reset_app():
    for k in list(st.session_state.keys()):
        del st.session_state[k]
    st.rerun()

# ================= PDF =================

def extract_pdf_text(uploaded_file):
    try:
        reader = PdfReader(uploaded_file)
        text = ""
        for page in reader.pages:
            if page.extract_text():
                text += page.extract_text() + "\n"
        return text
    except Exception as e:
        st.error(f"PDF extraction error: {e}")
        return ""

# ================= GROQ REPORT =================

def get_report(resume, job_desc):
    client = Groq(api_key=api_key)

    prompt = f"""
You are an AI Resume Analyzer used as an ATS replacement.

Analyze the resume against the job description.
Score each category out of 5.

Use:
✅ aligned
⚠️ partially aligned
❌ not aligned

Resume:
{resume}

---
Job Description:
{job_desc}

Categories:
- Skills
- Experience
- Projects
- Education
- ATS Readability

Format STRICTLY like:
Category Name: X/5 + emoji + short explanation

End with a FINAL HIRING VERDICT and POINTS TO IMPROVE RESUME.
"""

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )

    return completion.choices[0].message.content

# ================= SCORE EXTRACTION =================

def extract_scores(text):
    return [float(m) for m in re.findall(r'(\d+(?:\.\d+)?)/5', text)]

# ================= SCORE BADGE =================

def generate_score_badge(score_percent):
    img = Image.new("RGB", (500, 260), "#0f172a")
    draw = ImageDraw.Draw(img)

    try:
        font_big = ImageFont.truetype("arial.ttf", 60)
        font_mid = ImageFont.truetype("arial.ttf", 28)
        font_small = ImageFont.truetype("arial.ttf", 20)
    except:
        font_big = font_mid = font_small = ImageFont.load_default()

    draw.text((150, 20), "AI ATS SCORE", fill="white", font=font_mid)
    draw.text((170, 80), f"{score_percent}%", fill="#38bdf8", font=font_big)
    draw.text((90, 170), "Generated by AI Resume Analyzer", fill="#94a3b8", font=font_small)

    buffer = BytesIO()
    img.save(buffer, format="PNG")
    buffer.seek(0)
    return buffer

# ================= FORM =================

if not st.session_state.form_submitted:
    with st.form("resume_form"):
        resume_file = st.file_uploader("Upload Resume/CV (PDF)", type="pdf")
        st.session_state.job_desc = st.text_area(
            "Job Description",
            placeholder="Paste The Job Description Here...",
        )

        submitted = st.form_submit_button("🔍 Scan Resume")

        if submitted:
            if resume_file and st.session_state.job_desc.strip():
                st.session_state.resume = extract_pdf_text(resume_file)
                st.session_state.form_submitted = True
                st.rerun()
            else:
                st.warning("Please upload resume and job description.")

# ================= RESULTS =================

if st.session_state.form_submitted:

    st.subheader("⚙️ AI is analyzing your resume...")

    progress = st.progress(0)
    for i in range(100):
        time.sleep(0.02)
        progress.progress(i + 1)

    report = get_report(
        st.session_state.resume,
        st.session_state.job_desc
    )

    scores = extract_scores(report)
    ai_avg_score = (
        sum(scores) / (5 * len(scores))
        if scores else 0
    )

    st.session_state.ai_score = int(ai_avg_score * 100)

    # ===== Animated Score Reveal =====
    st.subheader("🧠 AI Match Score")
    score_placeholder = st.empty()

    for i in range(st.session_state.ai_score + 1):
        score_placeholder.metric("AI Avg Match Score", f"{i}%")
        time.sleep(0.015)

    # ===== Verdict =====
    st.subheader("🎯 Final Verdict")

    if ai_avg_score >= 0.8:
        st.success("🚀 STRONG MATCH – Highly Recommended for Shortlisting")
    elif ai_avg_score >= 0.5:
        st.warning("⚠️ MODERATE MATCH – Improvements Needed")
    else:
        st.error("❌ WEAK MATCH – Low Hiring Probability")
    # ===== Skill Match Analysis =====
    
    st.subheader("🛠️ Skill Match")
    if ai_avg_score >= 0.8:
        st.success("🟢 All required skills are well aligned with the job description.")
    elif ai_avg_score >= 0.5:
        st.warning("🟡 Some skills are partially aligned; consider enhancing relevant skills.")
    else:
        st.error("🔴 Key skills are missing or not aligned with the job description.")
        
    # ===== Score Badge =====
    st.subheader("🏷️ Shareable Resume Score Badge")

    badge = generate_score_badge(st.session_state.ai_score)
    st.image(badge, width=350)

    st.download_button(
        "📥 Download Score Badge",
        data=badge,
        file_name="resume_score_badge.png",
        mime="image/png"
    )

    # ===== Report =====
    st.subheader("🧠 AI Resume Analysis Report")
    st.markdown(
        f"<div style='background:#0f0f0f;padding:16px;border-radius:10px'>{report}</div>",
        unsafe_allow_html=True
    )

    st.download_button(
        "📥 Download Full Report",
        data=report,
        file_name="resume_analysis.txt"
    )

    st.divider()

    if st.button("🔁 Check Another Resume"):
        reset_app()
